### PR TITLE
Migrate to Puma application server

### PR DESCRIPTION
**Pull request by kenhys**
Puma is Now the Recommended Ruby Webserver
https://devcenter.heroku.com/changelog-items/594

Since January 2015, Puma is recommended web server
on Heroku.

### CODE REVIEW

**Comment by kenhys** [comment]
It should be merged after #131.

**Comment by ashie** [comment]
> It should be merged after #131.
> With #131 and #133, it works on heroku-16 stack.

I also confirmed that it works on both heroku-16 and heroku-20 stack.
Without this PR (#133) the app crashes due to memory consumption.
I'm considering following migration steps to heroku-20:

1. Merge #131.
2. Rebase this PR #133.
3. Upgrade to heroku-20 (not triggered yet)
4. Merge this PR #133 to trigger upgrading heroku stack

**Comment by ashie** [comment]
>     1. Merge #131.

Done. Could you rebase this PR? @kenhys 

BTW #131 isn't applied yet due to the following error:
https://app.circleci.com/pipelines/github/fluent/fluentd-website/85/workflows/49151be9-989f-4ec3-ab16-00617ad6fed5/jobs/575
```
To https://git.heroku.com/******************.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://heroku:************************************@git.heroku.com/******************.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
Probably this conflict occurred on migration trouble in yesterday.
We need to force push to clear it.

**Comment by kenhys** [comment]
@ashie I've rebased and resolve conflicts.

**Review by ashie — APPROVED** [review]
I've confirmed it on a staging site (both Heroku-16 and Heroku-20).

**Pull request merged**
