### PR TITLE
Reduce frequency to update plugins.json

### PR DESCRIPTION
**Pull request by kenhys**
Another approach #269 

Before:
  * Update plugins.json every day

After:
  * Update plugins.json when the number of plugin is changed.
  * Reduce commit just update "downloads" field. Note that "downloads" may be inaccurate.

### CODE REVIEW

**Review by ashie — CHANGES_REQUESTED** [review]
> * Reduce commit just update "downloads" field. Note that "downloads" may be inaccurate.

Even though it's inaccurate, it should be update at least per week.

**Comment by kenhys** [comment]
> Even though it's inaccurate, it should be update at least per week.

Thanks, surely it should be.

**Review by ashie — APPROVED** [review]

**Comment by ashie** [comment]
Thanks!

**Comment by ashie** [comment]
Failed running the job :thinking: 
https://github.com/fluent/fluentd-website/actions/runs/5810162637/job/15750503845

```
Run ruby scripts/plugins.rb
/opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/psych.rb:670:in `initialize': No such file or directory @ rb_sysopen - plugins.json (Errno::ENOENT)
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/psych.rb:670:in `open'
	from /opt/hostedtoolcache/Ruby/3.1.4/x64/lib/ruby/3.1.0/psych.rb:670:in `load_file'
	from scripts/plugins.rb:75:in `update'
	from scripts/plugins.rb:100:in `<main>'
```

**Comment by kenhys** [comment]
> Failed running the job 🤔

I'll fix it.

**Pull request merged**
