### PR TITLE
blog: add Fluentd v1.17.1 release announcement

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by kenhys** [comment]
TODO: add link to reuse_record.

**Comment by kenhys** [comment]
> TODO: add link to compress

done.

**Comment by kenhys** [comment]
> TODO: add link to reuse_record.

done. 

but https://github.com/fluent/fluentd-docs-gitbook/pull/515 is not merged yet.

**Review by daipom — COMMENTED** [review]
Thanks! I have commented on some points.

**Comment by kenhys** [comment]
Thanks, I've applied it.

**Review by daipom — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
