### PR TITLE
blog: Add Fluentd v1.16.4 release announcement

### PR DESCRIPTION
**Pull request by daipom**

### CODE REVIEW

**Comment by kenhys** [comment]
Cloud you explain a bit more detail to help user making it understand ?
e.g. https://www.fluentd.org/blog/fluentd-v1.16.2-v1.16.3-have-been-released

**Comment by daipom** [comment]
There seems to be little content for users to explain about this release.
But certainly, as you say, there may be some more content that could be explained.
I will consider it. Thanks!

**Comment by daipom** [comment]
@kenhys I have added details about the buffer fix!
I think we don't need detailed explanations of the other fixes in this version.

**Review by kenhys — APPROVED** [review]
LGTM.

**Comment by kenhys** [comment]
Thanks!

**Pull request merged**
