### PR TITLE
Prevent Tab Nabbing

### PR DESCRIPTION
**Pull request by cosmo0920**
This should be becoming a vulnerbility to invite users into a phishing page.
We shouldn't trust 3rd party page.

ref: https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>

### CODE REVIEW

**Comment by cosmo0920** [comment]
@ashie Could you kindly take a look?
From the reference page, current website contains vulnerability for attacker who uses phishing site.
This PR should be fix this kind of issues.

**Comment by ashie** [comment]
Why are you add it to only https://discuss.fluentd.org?
It seems that it should be added to all `target=_blank` links.

**Comment by cosmo0920** [comment]
This is because this vulnerability is only pointed out for https://discuss.fluentd.org.
Yep, we should do more preventions for tab nabbing.

**Comment by cosmo0920** [comment]
@ashie Do you have read/write permissions for cncf-fluentd-maintainers@lists.cncf.io mailing list? 
I think that @ashie and @kenhys should be also granted read/write permissions for it.

**Comment by cosmo0920** [comment]
Other links are related TreasureData, Fluentd, slideshare, youtube related pages.
Should we add `rel="nofollow noopener noreferrer"` for them?

**Comment by kenhys** [comment]
> Other links are TreasureData, Fluentd, slideshare, and youtube videos related pages.
Should we add rel="nofollow noopener noreferrer" for them?

Apparently, it may be less risky site, but  even though, it may be better not to trust an external site by default.
(IMHO, we should add)

**Comment by ashie** [comment]
FYI `rel=noopener` is applied by default on modern browsers

* Firefox: as of 79
* Chrome: as of 88
* Safari: as of 12.1

**Comment by ashie** [comment]
BTW is discuss.fluentd.org untrusted site?
It's under fluentd.org, and announced by @agup006 at https://groups.google.com/g/fluentd/c/z6e4ziIfzdo, so I thought it's a trusted site.

**Comment by kenhys** [comment]
> BTW is discuss.fluentd.org untrusted site?

No doubt that it is a trusted site, I should explain "we should keep safety even though these sites are compromised".

**Comment by ashie** [comment]
> No doubt that it is a trusted site, I should explain "we should keep safety even though these sites are compromised".

Sorry, it isn't a comment to you.
(I also think adding `rel="noopener noreferrer"` to all `targert=_blank` links is better.)
My interest is "why the vulnerability reported treated it as untrusted".

> @ashie Do you have read/write permissions for [cncf-fluentd-maintainers@lists.cncf.io](mailto:cncf-fluentd-maintainers@lists.cncf.io) mailing list?
> This vulnerability is reported there.

**Comment by ashie** [comment]
> (I also think adding rel="noopener noreferrer" to all targert=_blank links is better.)

On the other hand, I think adding `rel=nofollow` should be case by case, probably not needed in most cases.
We should understand this attribute correctly.
https://developers.google.com/search/docs/advanced/guidelines/qualify-outbound-links?hl=en

**Comment by cosmo0920** [comment]
> 
> 
> > (I also think adding rel="noopener noreferrer" to all targert=_blank links is better.)
> 
> On the other hand, I think adding `rel=nofollow` should be case by case, probably not needed in most cases.
> We should understand this attribute correctly.
> https://developers.google.com/search/docs/advanced/guidelines/qualify-outbound-links?hl=en

OK. I'll read it carefully.

**Comment by ashie** [comment]
> Why do you add it to only https://discuss.fluentd.org?
> It seems that it should be added to all target=_blank links.

Although I still want to hear the answer for it, at least adding `rel=noopener` to all `target=_blank` is reasonable.
Merge it.

**Comment by cosmo0920** [comment]
Thanks!

**Comment by ashie** [comment]
In addition, I think `rel=nofollow` isn't needed though.

**Pull request merged**
