### PR TITLE
blog: add v5.0.2 release announcement

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Review by daipom — APPROVED** [review]
LGTM. Thanks!

**Review by ashie — CHANGES_REQUESTED** [review]
Please update versions here: https://github.com/fluent/fluentd-website/blob/9f1527dbcb6f5a01748840b57cdb22893aeef9ca/app.rb#L57-L67

In addition, please update also v4 series to v4.5.2 in this PR.
To highlight v5.0.2 release, we won't post a separated article for v4.5.2.

**Review by ashie — APPROVED** [review]
I've added a commit to bump up versions.

**Comment by kenhys** [comment]
Thanks!

**Comment by kenhys** [comment]
> n addition, please update also v4 series to v4.5.2 in this PR.
To highlight v5.0.2 release, we won't post a separated article for v4.5.2.

Okay. I will add it.

**Comment by daipom** [comment]
> I've added a commit to bump up versions.

Sorry, I forgot! Thanks!

**Comment by kenhys** [comment]
I've added a bit about td-agent v4.5.2.

**Pull request merged**
