### PR TITLE
Added link to Manning book

### PR DESCRIPTION
**Pull request by mp3monster**
Hope this is ok. Added a blog post about the New Manning book on Fluentd. Added link on guides page to blog post

### CODE REVIEW

**Comment by ashie** [comment]
@mp3monster Sorry for my late response.

The contents seems O.K. for me.
Could you follow DCO?: https://github.com/fluent/fluentd-website/pull/180/checks?check_run_id=5511181615
(Add `Signed-off-by:` to your commit messages.)

**Review by ashie — CHANGES_REQUESTED** [review]
One more thing.
Could you add author's information like this?

https://github.com/fluent/fluentd-website/blob/88cfb18fb5852bd18d5f96de6b5542a1eddd8082/content/blog/20220209_fluentd-v1.14.5-has-been-released.md?plain=1#L54

https://github.com/fluent/fluentd-website/blob/88cfb18fb5852bd18d5f96de6b5542a1eddd8082/app.rb#L58-L88

**Comment by mp3monster** [comment]
Sorry, could you point me to where the sign off is obtained from ?

**Comment by kenhys** [comment]
DCO is explained at https://github.com/fluent/fluentd-website/pull/180/checks?check_run_id=5511181615 
Actual steps are explained like this:

image

**Comment by mp3monster** [comment]
can you confirm that Ive actioned the request properly please

**Comment by kenhys** [comment]
@mp3monster 

if you are working on repository which contains the following branch, 

```
% git remote -v
origin  git@github.com:mp3monster/fluentd-website.git (fetch)
origin  git@github.com:mp3monster/fluentd-website.git (push)
upstream        https://github.com/fluent/fluentd-website.git (fetch)
upstream        https://github.com/fluent/fluentd-website.git (push)
```

Maybe the following commands works.

```
git pull --rebase upstream master
git rebase HEAD~3 --signoff
```

NOTE: It is recommended to create a topic branch

**Pull request closed without merging**
