### PR TITLE
Add note for obsolete plugins

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
add note for obsolete plugins

**Comment by okkez** [comment]
This is useful for users to know reason and alternative way about obsolete plugins.

**Comment by repeatedly** [comment]
Could you rebase it?

**Comment by okkez** [comment]
Rebased.

**Comment by repeatedly** [comment]
Thanks!

**Comment by repeatedly** [comment]
@okkez After merged this patch, `bundle exec ruby scripts/test_5xx.rb ` failed. Could you check this?

**Comment by okkez** [comment]
Sure, I will check it later.

**Comment by okkez** [comment]
@repeatedly I've fixed and create #21

**Pull request merged**
