### PR TITLE
blog: Add v1.15.1 release announcement

### PR DESCRIPTION
**Pull request by daipom**
CHANGELOG: https://github.com/fluent/fluentd/blob/master/CHANGELOG.md#release-v1151---20220727

### CODE REVIEW

**Review by ashie — APPROVED** [review]
LGTM

**Comment by ashie** [comment]
Thanks!

**Comment by daipom** [comment]
Thanks for merging!

**Comment by ashie** [comment]
@daipom 

Could you increment the version in following line from next time you post a blog for new Fluentd release?

https://github.com/fluent/fluentd-website/blob/6887e58cb10a6e54ff97b333aec04f203c1c6868/app.rb#L37

It will be applied to the download page: https://www.fluentd.org/download

For this time, I'll do it when I update td-agent version to v4.4.0.

**Comment by daipom** [comment]
Sure! I will do it next time!

**Pull request merged**
