### PR TITLE
Add CNCF GA4 site tag

### LINKED ISSUE #234: CNCF access to analytics: setup GA4 in addition to HubSpot
Since July 6, 2020, the website is no longer sending events to the CNCF Google Analytics account. This is because the analytics access was _dropped_ via:

- #229

Using HubSpot is fine, but this issue is to request that GA4 analytics be setup as well.

Please ensure that the following snippet is added to all website pages:

```html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-93T2VC0VBC"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-93T2VC0VBC');
</script>
```

/cc @caniszczyk @amye

### PR DESCRIPTION
**Pull request by chalin**
- Closes #234

/cc @caniszczyk @edsiper

### CODE REVIEW

**Comment by fujimotos** [comment]
@chalin Right now we (ClearCode devs) are mostly doing the maintanance work for fluentd.org.

* See https://github.com/fluent/fluentd-website/pulls?q=is%3Apr+is%3Aclosed for recent updates.
* We post [release announces to blog](https://www.fluentd.org/blog/) and [update the plugin list](https://github.com/fluent/fluentd-website/commit/0aecd6687fc09c14c8fdd879b441f2d7cee5fc38).

But we have no access to that said GA. Can you give us an access to that account?

**Comment by chalin** [comment]
Hi @fujimotos - yes I can grant maintainers access; just provide me with a list of email addresses either here or you can reach me on the CNCF Slack.

Can this PR be merged?

**Comment by fujimotos** [comment]
> yes I can grant maintainers access; just provide me with a list of email addresses either here or you can reach me on the CNCF Slack.

@chalin Thank you! Here is the list of Google accounts of 
ClearCode's Fluentd team:

* fujimotos.clearcode@gmail.com
* reangoapyththeorem@gmail.com
* takuro.ashie@gmail.com


> Can this PR be merged?

Now I'm going to merge this PR.

**Comment by chalin** [comment]
Thank you for merging this PR @fujimotos. I've granted access to the email addresses listed above. You should have received a notification, if not, let me know.

**Comment by fujimotos** [comment]
>  I've granted access to the email addresses listed above.

@chalin Thank you! I can confirm that the access to the GA project was granted.

**Pull request merged**
